### ISSUE TITLE
Rename Theia Blueprint product

### ISSUE THREAD

**Issue by koegel** [eclipse-theia/theia-blueprint#177]
Currently we only have one Blueprint product to showcase Theia. This is about to change with CDT.cloud Blueprint and potentially Theia.cloud Blueprint. Therefore it would be good to give the current product a name, e.g. Theia WebDev Blueprint.
This would also mean that the current page at https://theia-ide.org/docs/blueprint_download needs to be slightly rephrased to talk about the "Theia Blueprint subproject" providing different blueprint products.

**Comment by koegel** [comment]
@marcdumais-work @JonasHelming @jfaltermeier @thegecko What do you think? Any suggestions for a name?

**Comment by JonasHelming** [comment]
From my POV, the current products work together nicely:

Theia Blueprint
Theia.cloud Blueprint
CDT.cloud Blueprint

CDT.cloud Blueprint does not have Theia in the name and that is on purpose, because it is targeted at C/C++ adopters.
I also think it is reasonable, that  Theia Blueprint has a focus, e.g. web developers, we can mention this in the description.
I kind of like the fact that there is a "Theia Blueprint" "vanilla".
When we introduce more Blueprints, we can think about adding new names. The most likely one is probably Java. For this, we could either name it:
Theia Blueprint for Java
or 
JDT.cloud Blueprint

So to answer the original question: I would not rename it right now, I think there should be one Blueprint as kind of the default.
If the default is not WebDev anymore I would name the WedDev Blueprint: Theia Blueprint for WebDevs

**Comment by brianking** [comment]
> CDT.cloud Blueprint does not have Theia in the name and that is on purpose, because it is targeted at C/C++ adopters. I also think it is reasonable, that Theia Blueprint has a focus, e.g. web developers, we can mention this in the description. I kind of like the fact that there is a "Theia Blueprint" "vanilla". When we introduce more Blueprints, we can think about adding new names. The most likely one is probably Java. For this, we could either name it: Theia Blueprint for Java or JDT.cloud Blueprint

I would argue against such fragmentation. Can we, wherever possible, just have the vanilla Blueprint optimized for as many use cases as possible and then provide documentation (e.g. what extensions to install, how to build, ...) for specific use cases?

The advantages of this would be at least 2-fold:

- lesser maintenance overhead
- shared branding and messaging around Theia Blueprint for a consistent end-user focus

**Comment by JonasHelming** [comment]
We just discussed this and Brian, Marc, Thomas and me would prefer the current state:

Theia Blueprint
Theia.cloud Blueprint
CDT.cloud Blueprint

**Comment by koegel** [comment]
OK, makes sense to me!
