### ISSUE TITLE
Update starts in background when Theia is closed even if user declined to update

### ISSUE THREAD

**Issue by ErikLundinSTM** [eclipse-theia/theia-blueprint#212]
### Bug Description:
When the user has been asked whether to install a newly downloaded Theia update and the answer was *No*, the update is executed when the application is closed. This can be confusing to a user and should be considered a bug, especially since the updates runs in the background. Trying to start Theia during the update typically shows various error messages, since while the old version is uninstalled and the new one is installed, files are removed and installed.

### Steps to Reproduce:

1. Download and install [an old version](https://www.eclipse.org/downloads/download.php?file=/theia/1.22.1/windows/TheiaBlueprint.exe&r=1) of Theia Blueprint
2. Check for updates (File > Preferences > Check for Updates)
3. Answer *Yes* when asked to download the new version
4. When asked whether to update now, answer *No*
5. Close Theia
6. Watch as the old version is uninstalled and the new is installed (e.g. processes running, files in `%LOCALAPPDATA%/Programs/TheiaBlueprint` that disappear and get replaced, non working start menu shortcut, etc.)
7. When the update has finished, the new version works as it should

![image](https://user-images.githubusercontent.com/95412924/160405263-fba1763a-13ca-4187-91d1-54bece6c3461.png)

### Additional Information

- Operating System: Windows
- Theia Version: 1.22.1

**Comment by jfaltermeier** [comment]
Thanks for the report. We are using `electron-updater` for this functionality. We should probably adjust the wording to reflect what is actually going on, since the `electron-updater` will automatically install the update, after a successful download, when the application is closed. 

My current suggestion would be 
"The update was downloaded and will be installed when the application gets closed. Do you want to restart the application now?"

**Comment by ErikLundinSTM** [comment]
So we don't have the possibility to make electron-updater ask again and only when the user has explicitly accepted to install the update do it?

**Comment by jfaltermeier** [comment]
It starts with the "Updates found, do you want to download the update? - No, Yes, Never" Popup. 
When the user selects no it will ask again on the next start or when invoked via Menu Bar -> File -> Preferences -> Check for Updates
When the user selects yes the update will be performed. Since the update requires the restart, we open this second dialog asking whether the restart should happen now. 
Maybe we should make it more clear in the first popup that this will already start the update process: "Updates found, do you want to update?"
