### ISSUE TITLE
Theia electron installer on windows has a hard coded default path

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia-blueprint#35]
### Bug Description:

 - Download the installer from here https://download.eclipse.org/theia/1.9.1/windows/
 - Install
 - See the default path

![image](https://user-images.githubusercontent.com/1405703/106894088-c21f1a80-66ee-11eb-8f1a-887c5fd0c8a7.png)

### Steps to Reproduce:

1.
2.
3.

### Additional Information

- Operating System:
- Theia Version:

**Comment by vince-fugnitto** [comment]
@kittaakos I transferred the issue to the `theia-example` repository, if it’s incorrect please let me know 👍

**Comment by koegel** [comment]
Thanks for reporting this, that needs to be fixed for the beta.

**Comment by DukeNgn** [comment]
I confirmed the issue on Windows. However, it only happens when I chose the option to install for all users. When installing `only for me`, the path is correctly customized based on my machine.

![image](https://user-images.githubusercontent.com/43587865/115565242-36e20980-a287-11eb-821e-bfc8a0c0d3ef.png)

**Comment by jfaltermeier** [comment]
This is taken from the electron-app package.json's author field. 
What should we take as the organisation name? Some suggestions:

- Eclipse
- Eclipse Theia
- Eclipse Foundation

**Comment by koegel** [comment]
I suggest "Eclipse Theia"
