### ISSUE TITLE
logo: improve logo design

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia-blueprint#91]
#### Feature Description:

I believe the **eclipse theia blueprint** logo can be improved based on feedback (internal and my own).

<br />

<div align='center'>

![image](https://user-images.githubusercontent.com/40359487/117204274-186b2a80-adbe-11eb-8a39-743ea7bcb3f4.png)

</div>

<br />

There are a few areas of the logo that can be improved, namely:

- there are too many unnecessary shades of blue present in the overall logo, namely the word `blueprint`.
- the logo currently uses two different fonts.
- the logo is currently misaligned (ex: the words `theia` and `blueprint`).

I believe fixing these issues, and possibly others will make for an overall better logo, and be more professional for a product.
The logo is one of the first thing new and existing users will notice, and we should ensure that it positively reflects the product.

**Comment by JonasHelming** [comment]
@brianking

**Comment by croundy** [comment]
Thanks for that feedback @vince-fugnitto. I agree with you that thee logo could be better. However, before asking Mehrnaz to do anything more with this design, I would like to get a +1 and input from @JonasHelming as the design was driven by his team.  As you may recall, the shade of blue used for the Blueprint text was actually insisted upon against recommendations made by our designer. 

To your other points, it's not uncommon in logo designs to use 2 different fonts, especially where the primary font is that of the  original logo/brand.  Would like feedback/guidance on whether the group would like to use the same font as the Theia logo font, or if the issue is more about the spacing of the "Blueprint" text. As for alignment, "Blueprint" is aligned with the vertical line of the T. Are you suggesting to align with the horizontal line, or again, is this more about using a font, size and spacing that better fills the space under Theia?

**Comment by JonasHelming** [comment]
@koegel

**Comment by koegel** [comment]
Probably I am biased since I was very much involved with designing the logo as is, anyway I have to say I like the logo as is. About the points @vince-fugnitto is bringing up:

- colors: I do not see a problem with the different shades of blue, but I would also not see a problem if "blueprint" had the same color as "Theia"
- fonts: I agree with @croundy that this is not uncommon
- alignment: For me the logo and the print seem aligned "enough" but I would not be opposed to changing something if you have some recommendation @vince-fugnitto

**Comment by croundy** [comment]
See what you think of this:

![image](https://user-images.githubusercontent.com/72274403/118507275-508e3980-b6eb-11eb-9776-a36b19dbab49.png)

**Comment by vince-fugnitto** [comment]
> See what you think of this:
> 
> ![image](https://user-images.githubusercontent.com/72274403/118507275-508e3980-b6eb-11eb-9776-a36b19dbab49.png)

I personally think it looks much better, the issues I had with the original are fixed :+1: It looks more polished overall.

**Comment by koegel** [comment]
Looks good to me!

**Comment by koegel** [comment]
We will add this to Blueprint for the Beta 2 milestone
